deploy to ec2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -51,15 +51,22 @@ jobs:
           key: ${{ secrets.EC2_SSH_KEY }}
           port: ${{ secrets.EC2_PORT}}
           script: |
-            # Log in to AWS ECR on the EC2 instance
-            aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 879602785537.dkr.ecr.ap-southeast-1.amazonaws.com
+              ssh -o StrictHostKeyChecking=no -i agriculture.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
+              set -e  # Exit immediately if a command fails
 
-            # Pull the latest image
-            sudo docker pull 879602785537.dkr.ecr.ap-southeast-1.amazonaws.com/argo-repo:latest
-            
-            # Stop and remove the old container if it exists
-            sudo docker stop frontend || true
-            sudo docker rm frontend || true
-            
-            # Run the new containers
-            sudo docker run -d --name frontend -p 3000:3000 879602785537.dkr.ecr.ap-southeast-1.amazonaws.com/argo-repo:latest
+              echo "Logging in to Amazon ECR..."
+              aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 879602785537.dkr.ecr.ap-southeast-1.amazonaws.com
+
+              echo "Pulling latest Docker image..."
+              sudo docker pull 879602785537.dkr.ecr.ap-southeast-1.amazonaws.com/agro-repo:latest
+
+              echo "Stopping and removing existing container if exists..."
+              sudo docker stop react-app || true
+              sudo docker rm react-app || true
+
+              echo "Running new container..."
+              sudo docker run -d -p 3000:3000 --name react-app 879602785537.dkr.ecr.ap-southeast-1.amazonaws.com/agro-repo:latest
+
+              echo "Deployment complete."
+              EOF
+      
