deploy to ec2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -38,41 +38,29 @@ jobs:
 
   deploy:
     runs-on: ubuntu-latest
-    needs: build  # This ensures the deploy job runs after the build job
+    needs: build
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Setup SSH key
-        run: |
-          echo "${{ secrets.EC2_SSH_KEY }}" > agriculture.pem
-          sudo chmod 400 agriculture.pem
-
-        
       - name: Deploy code to EC2
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
-          port: ${{ secrets.EC2_PORT}}
+          port: ${{ secrets.EC2_PORT }}
           script: |
-              sudo ssh -o StrictHostKeyChecking=no -i agriculture.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
-              set -e  # Exit immediately if a command fails
+            set -e  # Exit immediately if a command fails
 
-              echo "Logging in to Amazon ECR..."
-              aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 879602785537.dkr.ecr.ap-southeast-1.amazonaws.com
+            echo "Logging in to Amazon ECR..."
+            aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 879602785537.dkr.ecr.ap-southeast-1.amazonaws.com
 
-              echo "Pulling latest Docker image..."
-              sudo docker pull 879602785537.dkr.ecr.ap-southeast-1.amazonaws.com/argo-repo:latest
+            echo "Pulling latest Docker image..."
+            docker pull 879602785537.dkr.ecr.ap-southeast-1.amazonaws.com/argo-repo:latest
 
-              echo "Stopping and removing existing container if exists..."
-              sudo docker stop react-app || true
-              sudo docker rm react-app || true
+            echo "Stopping and removing existing container if exists..."
+            docker stop react-app || true
+            docker rm react-app || true
 
-              echo "Running new container..."
-              sudo docker run -d -p 3000:3000 --name react-app 879602785537.dkr.ecr.ap-southeast-1.amazonaws.com/argo-repo:latest
+            echo "Running new container..."
+            docker run -d -p 3000:3000 --name react-app 879602785537.dkr.ecr.ap-southeast-1.amazonaws.com/argo-repo:latest
 
-              echo "Deployment complete."
-              EOF
-      
+            echo "Deployment complete."
